[pytest]
testpaths = scripts/data_modules/tests scripts/tests
pythonpath = scripts
asyncio_mode = auto
addopts = -p no:debugging -p pytest_cov -q --cov --cov-report=term-missing --cov-fail-under=90 -p no:cacheprovider
